### ISSUE TITLE
Missing Color in Hollow Dark Theme for Several Functions

### ISSUE THREAD

**Issue by HarshChauhan18** [SmitAkbari26/HollowDark#1]
The current version of the hollow dark theme in our application seems to be missing color for several functions. As a result, some functions appear to blend in with the background, making it difficult for users to locate and access them. This issue has been reported by several users who are experiencing difficulties while using the application.
it was found that several functions, including [**pymysql.connect()**], are not displaying the correct color in the hollow dark theme. This is causing us as a user to appear dull and blend in with the background, making it difficult for us as a user to locate them. This issue is affecting the overall usability of the application.

![image](https://user-images.githubusercontent.com/107744227/232467543-5df18c26-1618-42c9-9216-8373359e17ca.png)

![image](https://user-images.githubusercontent.com/107744227/232468128-f86bca23-394f-42a5-ba39-d187fed70b5b.png)

![image](https://user-images.githubusercontent.com/107744227/232469210-7f13681b-90c0-420b-9e86-d35275bba609.png)

**Comment by SmitAkbari26** [comment]
We understand that the hollow dark theme is a popular choice among our users, and we want to ensure that it works as intended. Therefore, we are actively working on a fix to address this issue. Our team is currently working on identifying the root cause and implementing a solution to ensure that all functions in the hollow dark theme display the correct color.

We apologize for any inconvenience caused by this issue, and we appreciate your patience while we work to resolve it. If you have any further questions or concerns regarding this issue, please feel free to reach out to us, and we will be happy to assist you.

**Comment by SmitAkbari26** [comment]
I hope v2.3.3 fix your issue.
